Changes in prep for SUSper

diff --git a/vncmgr b/vncmgr
--- a/vncmgr
+++ b/vncmgr
@@ -4,24 +4,24 @@
 #   VNC sessions on the Casper cluster.
 #
 #   Author:         Brian Vanderwende
-#   Last Revised:   12:15, 18 Jan 2023
+#   Last Revised:   13:35, 07 Sep 2023
 #
 
 # Make sure environment is configured to run VNC jobs
 . /etc/profile >& /dev/null
 my_dir="$( cd "$(dirname "$0")" ; pwd )"
 cd $HOME; mkdir -p .vncmgr
-module load ncarenv
+module -q load ncarenv
 
 # Default values for jobs
 def_walltime=4:00:00
-def_shell=startkde
 
 # qstat display settings
 qstat_bin=/glade/u/apps/opt/qstat-cache/qstat
 qstat_fmt="%-9.9s %-16s %2s %4s %7s %14s\n"
 qstat_labels="JobID Name S NCPU ReqMem Time(HH:MM)"
 qstat_splits="----- ---- - ---- ------ -------------"
+export QSCACHE_DEBUG=0
 
 function usage {
 cat << EOF
@@ -55,8 +55,6 @@ Create Command Options
                                 (or use \$DAV_PROJECT env variable)
         -t, --time=WALLTIME     length of time that the PBS job
                                 will perist (man qsub for format)
-        -d, --desktop=SHELL     type of desktop shell VNC will use
-                                (2d, gnome-session, or startkde)
         -j, --job-opts="OPTS"   additional arguments to pass to the
                                 qsub command (see man qsub)
         -v, --vnc-opts="OPTS"   arguments to pass to the vncserver
@@ -119,6 +117,29 @@ Options:
 EOF
 }
 
+function check_password {
+    if [[ ! -f ~/.vnc/passwd ]]; then
+        echo "Warning: VNC servers should be password protected to prevent unauthorized"
+        echo "         access, but you do not have a password configured."
+
+        if ! which vncpasswd >& /dev/null; then
+            >&2 echo "Error: vncpasswd command is not available on this host. Please retry or run"
+            >&2 echo "       the command manually on a login node."
+            exit 1
+        else
+            echo -e "\nPlease configure your VNC password now..."
+            echo -e "(VNC only supports passwords between 6 and 8 characters)\n"
+
+            if ! vncpasswd; then
+                >&2 echo "Error: password configuration unsuccessful. Exiting."
+                exit 1
+            else
+                echo
+            fi
+        fi
+    fi
+}
+
 function check_server {
     SECONDS=0
     echo "Waiting for VNC server to initialize ..."
@@ -142,7 +163,7 @@ function check_server {
         host_port=$((host_disp + 5900))
     else
         >&2 echo "Error: unexpected output from VNC server. Cancelling job."
-        qdel ${vnc_jobid}.$NCAR_PBS_CA >& /dev/null
+        qdel ${vnc_jobid}.casper-pbs >& /dev/null
         check_job_status ""
         >&2 echo -e "VNC output:\n"
         >&2 cat .vncmgr/$job_name
@@ -174,16 +195,24 @@ function check_job_status {
 function create_job {
     # Make sure job_opts includes necessary settings
     if [[ ${VNCMGR_BYPASS_CHECKS,,} != true ]]; then
-        if [[ $job_opts == *":ngpus="* ]]; then
-            if [[ ! $job_opts =~ .*:ngpus=1[:\ ].* ]]; then
+        if [[ $job_opts == *"select="* ]]; then
+            if [[ $job_opts == *":ngpus="* ]]; then
+                if [[ ! $job_opts =~ .*:ngpus=1[:\ ].* ]]; then
+                    opt_msg=True
+                    echo "Resource chunks must have ngpus=1; altering custom PBS options ..."
+                    job_opts=$(sed 's|:ngpus=[1-9]*|:ngpus=1|' <<< $job_opts)
+                fi
+            else
                 opt_msg=True
                 echo "Resource chunks must have ngpus=1; altering custom PBS options ..."
-                job_opts=$(sed 's|:ngpus=[1-9]*|:ngpus=1|' <<< $job_opts)
+                job_opts=$(sed 's|\(select=[^ ]*\)|\1:ngpus=1|' <<< $job_opts)
             fi
-        elif [[ $job_opts == *"select="* ]]; then
-            opt_msg=True
-            echo "Resource chunks must have ngpus=1; altering custom PBS options ..."
-            job_opts=$(sed 's|\(select=[^ ]*\)|\1:ngpus=1|' <<< $job_opts)
+
+            if [[ $job_opts == *":os="* ]]; then
+                opt_msg=True
+                echo "Chunks must specify os type; altering custom PBS options ..."
+                job_opts=$(sed 's|\(select=[^ ]*\)|\1:os=opensuse15|' <<< $job_opts)
+            fi
         fi
 
         if [[ $job_opts == *"gpu_type="* ]]; then
@@ -198,9 +227,13 @@ function create_job {
             vncmgr_queue=$(sed -n -E 's|.*-q ?([^ ]*).*|\1|p' <<< $job_opts)
             
             if [[ $vncmgr_queue != casper@casper-pbs ]] && [[ $csg_mode != true ]]; then
-                opt_msg=True
-                echo "-q must be set to casper@casper-pbs; altering custom PBS options ..."
-                job_opts=$(sed -E 's|-q ?[^ ]*|-q casper@casper-pbs|' <<< $job_opts)
+                echo "Warning: queue $vncmgr_queue may not support VNC rendering"
+                read -e -p "Are you sure you wish to continue (y/N)? " user_override
+                user_override=$(tr '[:upper:]' '[:lower:]' <<< $user_override)
+
+                if [[ yes != ${user_override:-no}* ]]; then
+                    exit
+                fi
             fi
         fi
     fi
@@ -212,8 +245,7 @@ function create_job {
     job_project=${job_project:-$DAV_PROJECT}
     job_walltime=${job_walltime:-$def_walltime}
     job_args="$job_opts -A $job_project -l walltime=$job_walltime -N $job_name -o .vncmgr/$job_name"
-    desktop_setup="TVNC_WM=${vnc_desktop:-$def_shell}"
-    export desktop_setup vnc_opts my_dir
+    export vnc_opts my_dir
 
     if [[ -z $job_project ]]; then
         >&2 echo -e "\nError: no valid project account given for PBS job"
@@ -222,7 +254,7 @@ function create_job {
     fi
 
     echo "Creating new VNC session ($vnc_session) ..."
-    envsubst '$desktop_setup $vnc_opts $my_dir' < $my_dir/.jobscript > .vncmgr/script.pbs
+    envsubst '$vnc_opts $my_dir' < $my_dir/.jobscript > .vncmgr/script.pbs
     echo -e "\n# User opts: vncmgr $user_args" >> .vncmgr/script.pbs
     echo "# qsub opts: qsub $job_args .vncmgr/script.pbs" >> .vncmgr/script.pbs
 
@@ -259,7 +291,7 @@ are given for both direct remote access via tunneling and access via the UCAR VP
 
   Create an SSH tunnel to stream desktop data to your local computer:
 
-    ssh -l $USER -L $host_port:localhost4:$host_port $host_addr "bash ~/.vncmgr/tunnel-$vnc_session"
+    ssh -l $USER -L $host_port:localhost:$host_port $host_addr "bash ~/.vncmgr/tunnel-$vnc_session"
   
   Follow instructions given in local terminal. The local terminal session will
   hang after creating the tunnel. This behavior is normal.
@@ -313,26 +345,12 @@ function query_job {
 function kill_job {
     if [[ ${vnc_jobid}z != z ]]; then
         echo "Cancelling VNC session ($vnc_session) with job ID $vnc_jobid ..."
-        qdel ${vnc_jobid}.$NCAR_PBS_CA >& /dev/null
+        qdel ${vnc_jobid}.casper-pbs >& /dev/null
         echo "Waiting for job records to refresh ..."
         check_job_status ""
     else
         >&2 echo "No session found with name $vnc_session"
     fi
-}
-
-function map_desktop {
-    case $vnc_desktop in
-        gnome2|GNOME2)
-            vnc_desktop=2d
-            ;;
-        gnome3|GNOME3)
-            vnc_desktop=gnome-session
-            ;;
-        kde|KDE)
-            vnc_desktop=startkde
-            ;;
-    esac
 }
 
 function live_driver {
@@ -353,17 +371,15 @@ function live_driver {
         else
             clear
             echo -e "\nUse these options to configure your VNC desktop session and PBS job."
-            echo "The maximum time allowed for a job is 24:00:00. Available desktop shells"
-            echo -e "include 2d (GNOME2), gnome-session (GNOME3), and startkde (KDE).\n"
+            echo "The maximum time allowed for a job is 24:00:00. You will be placed into"
+            echo -e "a Plasma5 KDE shell.\n"
 
             read -e -p "Enter project code for VNC job (default=$DAV_PROJECT): " job_project
             read -e -p "Enter time limit for VNC job (default=$def_walltime): " job_walltime
-            read -e -p "Choose desktop shell for VNC job (default=$def_shell): " vnc_desktop
             read -e -p "Additional PBS arguments for VNC job (optional): " job_opts
             read -e -p "Arguments to forward to vncserver program (optional): " vnc_opts
             echo
 
-            map_desktop
             create_job
             display_job
         fi
@@ -426,10 +442,6 @@ if [[ $# -gt 0 ]]; then
                         ;;
                     -t|--time*)
                         [[ $1 == *=* ]] && job_walltime=${1#*=} || read_value=job_walltime
-                        ;;
-                    -d|--desktop*)
-                        [[ $1 == *=* ]] && vnc_desktop=${1#*=} || read_value=vnc_desktop
-                        map_desktop
                         ;;
                     -j|--job-opts*)
                         [[ $1 == *=* ]] && job_opts=${1#*=} || read_value=job_opts
