Fixed bug in project detection error

diff --git a/vncmgr b/vncmgr
--- a/vncmgr
+++ b/vncmgr
@@ -4,7 +4,7 @@
 #   VNC sessions on the Casper cluster.
 #
 #   Author:         Brian Vanderwende
-#   Last Revised:   15:50, 28 Sep 2020
+#   Last Revised:   08:09, 30 Sep 2020
 #
 
 # Make sure environment is configured to run VNC jobs
@@ -128,6 +128,12 @@ function create_job {
     job_walltime=${job_walltime:-$def_walltime}
     desktop_setup="TVNC_WM=${vnc_desktop:-$def_shell}"
     export desktop_setup vnc_opts my_dir
+
+    if [[ -z $job_project ]]; then
+        echo -e "\nError: no core-hour account given for Slurm job"
+        echo "       specify $PERRMSG or with DAV_PROJECT variable"
+        exit 1
+    fi
 
     echo "Creating new VNC session ($vnc_session) ..."
     envsubst '$desktop_setup $vnc_opts $my_dir' < $my_dir/.${job_shell}script > .vncscript.slurm
@@ -261,6 +267,7 @@ function live_driver {
     query_session ${user_opts[1]}
 
     if [[ create == ${user_opts[0]}* ]]; then
+        PERRMSG="interactively"
         if [[ ${vnc_jobid}z != z ]]; then
             echo "Error: VNC session with name $vnc_session already exists"
         else
@@ -274,12 +281,6 @@ function live_driver {
             read -e -p "Choose desktop shell for VNC job (default=$def_shell): " vnc_desktop
             read -e -p "Additional Slurm arguments for VNC job (optional): " job_opts
             read -e -p "Arguments to forward to vncserver program (optional): " vnc_opts
-
-            if [[ -z $job_project ]]; then
-                echo -e "\nError: no core-hour account given for Slurm job"
-                echo "       enter interactively or specify using DAV_PROJECT variable"
-                exit 1
-            fi
 
             map_desktop
             create_job
@@ -298,6 +299,8 @@ function live_driver {
 
 # Run in batch if arguments, otherwise use live mode
 if [[ $# -gt 0 ]]; then
+    PERRMSG="using -A flag"
+
     # Help flag intercept
     if [[ " $@ " == *" --help "* ]] || [[ " $@ " == *" -h "* ]]; then
         usage
@@ -362,12 +365,6 @@ if [[ $# -gt 0 ]]; then
 
             shift
         done
-
-        if [[ -z $job_project ]]; then
-            echo "Error: no core-hour account given for Slurm job"
-            echo "       specify using -A flag or DAV_PROJECT variable"
-            exit 1
-        fi
 
         create_job
         display_job
